# manipulator:
#  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
#  kinematics_solver_timeout: 0.005
#  # kinematics_solver_attempts: 3

 # manipulator:
 #  kinematics_solver: ur_kinematics/UR5KinematicsPlugin
 #  kinematics_solver_search_resolution: 0.005
 #  kinematics_solver_timeout: 0.005
 #  kinematics_solver_attempts: 3

 manipulator:
   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
   kinematics_solver_search_resolution: 0.005
   kinematics_solver_timeout: 0.005
   kinematics_solver_attempts: 3

 # manipulator:
 #   kinematics_solver: ur5e_manipulator/IKFastKinematicsPlugin
 #   kinematics_solver_search_resolution: 0.005
 #   kinematics_solver_timeout: 0.005
 #   kinematics_solver_attempts: 3

 # manipulator:
 #  kinematics_solver: bio_ik/BioIKKinematicsPlugin
 #  kinematics_solver_search_resolution: 0.005
 #  kinematics_solver_timeout: 0.02
 #  kinematics_solver_attempts: 1
 #  mode: gd_c
