# Camera parameters
link:
  name: camera_link
  length: 0.05
  radius: 0.005
  origin: 
      xyz: 0 0 0
      rpy: 1.57079632679 0 1.57079632679
  inertial:
    mass: 0.01
    origin: 
      xyz: 0 0 0
      rpy: 1.57079632679 0 1.57079632679
    inertia: 
      ixx: 0.00001
      ixy: 0.0
      ixz: 0.0
      iyy: 0.000001
      iyz: 0.0
      izz: 0.000013

# Modify pitch to control camera tit with -pi/4 straight down, 0 looking at gripper.
#  XYZ is like tcp with z in grasp direction
joint:
  name: camera_joint
  parent_link: wrist_3_link
  origin: 
      xyz: 0 -0.06 0.025
      rpy: 3.14159265359 -1.32 1.57079632679

camera:
  name: camera_base
  pose: 0 0 0 0 0 0
  update_rate: 15
  horizontal_fov: 0.78539816339
  image:
    width: 800
    height: 800
    format: R8G8B8
  clip:
    near: 0.02
    far: 300
  # Noise is sampled independently per pixel on each frame. 
  #  That pixel's noise value is added to each of its color
  #  channels, which at that point lie in the range [0,1]
  noise_type: gaussian
  noise_mean: 0
  noise_stddev: 0.003
  plugin:
    # Plugin configuration values from source file at:
    #  github.com/ros-simulation/gazebo_ros_pkgs/blob/231a7219b36b8a6cdd100b59f66a3df2955df787/gazebo_plugins/src/gazebo_ros_camera_utils.cpp
    always_on: true
    camera_name: camera_base
    image_topic_name: image_raw
    camera_info_topic_name: camera_info
    cx_prime:      0        # rectified optical center x, for sim, CxPrime == Cx
    cx:            0        # optical center x
    cy:            0        # optical center y
    focal_length:  0        # also known as focal length
    hack_baseline: 0     # also known as focal length
    distortion_k1: 0        # linear distortion
    distortion_k2: 0        # quadratic distortion
    distortion_k3: 0        # cubic distortion
    distortion_t1: 0        # tangential distortion
    distortion_t2: 0        # tangential distortion
