# FT sensor parameters
link:
  name: ft_sensor_link
  length: 0.03
  radius: 0.035
  origin: 
      xyz: 0 0 0
      rpy: 0 0 0
  inertial:
    mass: 0.1
    origin: 
      xyz: 0 0 0.0125
      rpy: 0 0 0
    inertia: 
      ixx: 0.0001
      ixy: 0.0
      ixz: 0.0
      iyy: 0.00001
      iyz: 0.0
      izz: 0.00013
joint:
  name: ft_sensor_joint
  parent_link: wrist_3_link
  origin: 
      xyz: 0 0 0.015  # z = half of length
      rpy: 0 0 0
sensor:
  topic_name: ft_sensor/raw_data
  name: ft_sensor
  always_on: true
  visualize: true
  measure_direction: child_to_parent
  pose: 0 0 0 0 0 0
  update_rate: 50
  noise_type: gaussian
  noise_mean: 0
  noise_stddev: 0.003
